<?xml version="1.0" encoding="UTF-8"?>
<project basedir="." default="build" name="Korat">

    <property environment="env" />
    <property name="BUILD_DIR" value="build" />
    <property name="DISTRIB_DIR" value="dist" />
    <property name="TEST_REPORTS_DIR" value="test-reports" />

    <path id="Korat.classpath">
        <pathelement location="${BUILD_DIR}" />
        <pathelement location="lib/org.alloytools.alloy.dist.jar" />
        <pathelement location="lib/commons-cli-1.0.jar" />
        <pathelement location="lib/javassist.jar" />
        <pathelement location="lib/junit.jar" />
    </path>

    <target name="help">
        <echo>
        Korat build options: 
                build             -- builds Korat from source
                createJar         -- creates korat.jar from source
                test              -- runs some tests for Korat
                javadoc           -- builds JavaDoc for Korat API
        </echo>
    </target>

    <target name="clean">
        <delete dir="${BUILD_DIR}" />
        <delete dir="${DISTRIB_DIR}" />
        <delete dir="${TEST_REPORTS_DIR}" />
    </target>

    <target name="init">
        <fail message="Korat requires JDK 17 or later. Set JAVA_HOME to a supported JDK.">
            <condition><not><javaversion atleast="17" /></not></condition>
        </fail>
        <mkdir dir="${BUILD_DIR}" />
        <copy includeemptydirs="false" todir="${BUILD_DIR}">
            <fileset dir="src" excludes="**/*.java" />
        </copy>
        <copy includeemptydirs="false" todir="${BUILD_DIR}">
            <fileset dir="examples" excludes="**/*.java" />
        </copy>
        <copy includeemptydirs="false" todir="${BUILD_DIR}">
            <fileset dir="tests" excludes="**/*.java" />
        </copy>
    </target>

    <target name="build" depends="init">
        <echo message="${ant.project.name}: ${ant.file}" />
        <javac debug="true" debuglevel="source,lines,vars" destdir="${BUILD_DIR}" release="17" includeantruntime="false">
            <src path="src" />
            <src path="examples" />
            <src path="tests" />
            <classpath refid="Korat.classpath" />
        </javac>
    </target>

    <target name="createJar">
        <antcall target="clean" />
        <antcall target="build" />
        <mkdir dir="${DISTRIB_DIR}" />
        <copy todir="${DISTRIB_DIR}/lib"><fileset dir="lib" includes="*.jar" excludes="alloy4viz.jar" /></copy>
        <copy todir="${DISTRIB_DIR}">
            <fileset dir="." includes="README.txt,LICENSE.txt,CHANGES.md" />
        </copy>
        <copy todir="${DISTRIB_DIR}/lib">
            <fileset dir="lib" includes="*LICENSE*,DEPENDENCIES.txt" excludes="alloy4viz-LICENSE.txt" />
        </copy>
        <jar destfile="${DISTRIB_DIR}/korat.jar" basedir="${BUILD_DIR}">
            <manifest>
                <attribute name="Class-Path" value="lib/org.alloytools.alloy.dist.jar lib/commons-cli-1.0.jar lib/javassist.jar lib/junit.jar" />
                <attribute name="Main-Class" value="korat.Korat" />
            </manifest>
        </jar>
    </target>

    <target name="test" depends="build">
        <java classname="junit.textui.TestRunner" fork="true" failonerror="true">
            <classpath refid="Korat.classpath" />
            <jvmarg value="-Djava.awt.headless=true" />
            <arg value="korat.AllTests" />
        </java>
    </target>

    <target name="javadoc">
        <javadoc access="private" author="true" classpath="lib/org.alloytools.alloy.dist.jar;lib/commons-cli-1.0.jar;lib/javassist.jar;lib/junit.jar" destdir="web/api" doctitle="Korat API" nodeprecated="false" nodeprecatedlist="false" noindex="false" nonavbar="false" notree="false" source="17" sourcepath="src;tests;examples" splitindex="true" use="true" version="true">
            <fileset dir="src">
                <include name="korat/**/*.java" />
            </fileset>
            <link href="http://jakarta.apache.org/commons/cli/api-release/" />
            <link href="http://www.csg.is.titech.ac.jp/~chiba/javassist/html/" />
            <link href="http://junit.sourceforge.net/javadoc/" />
            <link href="http://java.sun.com/j2se/1.5.0/docs/api/" />
        </javadoc>
    </target>

</project>
